apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-printer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-printer
  template:
    metadata:
      labels:
        app: time-printer
    spec:
      containers:
        - name: time-printer
          image: davetool1234/final_project:v0.1
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
